return unless platform_family?("rhel")

package 'openssl-devel'
package 'libyaml-devel'
package 'nc'
package 'xterm'
package 'net-snmp-utils'
package 'telnet'
package 'strace'
package 'pylint'
package 'libxml2'
package 'libxml2-devel'
package 'libxslt-devel'
package 'libxslt'
package 'httpd'
package 'ncurses-devel'
